### ISSUE TITLE
Gesture Handler requires correction on Android

### ISSUE THREAD

**Issue by AlbertoCentonze** [uniconnect-epfl/uniconnect#44]

**Comment by Aidasvenc** [comment]
In android, `App.tsx` needs to be wrapped as follows:
![image](https://github.com/uniconnect-epfl/uniconnect/assets/79483254/5ee52844-f575-4d4e-afef-f4dd66e354f2)

Read more about it at https://docs.swmansion.com/react-native-gesture-handler/docs/fundamentals/installation
