### ISSUE TITLE
Profile page - main information

### ISSUE THREAD

**Issue by Aidasvenc** [uniconnect-epfl/uniconnect#54]
Implement a first look for a user's own profile page.

**Comment by GaelCondeLosada** [comment]
Put it as a few tasks in sprint backlog

**Comment by GaelCondeLosada** [comment]
Put it in the form of a few tasks in the sprint backlog.

**Comment by GaelCondeLosada** [comment]
Put it in the form of a few tasks in the sprint backlog.
