### ISSUE TITLE
Firebase API + secrets

### ISSUE THREAD

**Issue by GustaveCharles** [uniconnect-epfl/uniconnect#7]
- [x] #18
 - [x] #19

There should be a .env file in your .giignore that prevents accidental pushes, and you should use that file to store them when developing locally.

**Comment by AlbertoCentonze** [comment]
@Aidasvenc should we already add react-query-firebase?

**Comment by Aidasvenc** [comment]
> [@Aidasvenc](https://github.com/Aidasvenc) should we already add react-query-firebase?

Looks 🔥 but need to check if it works with React Native out of the box.
